/**
 * GET /firebase-messaging-sw.js
 *
 * Serves the Firebase Cloud Messaging service worker dynamically,
 * embedding the NEXT_PUBLIC_ Firebase config at runtime.
 *
 * Why dynamic? Service workers run in a separate JS context where
 * process.env and import.meta.env are NOT available. Serving it as
 * a Next.js route allows us to inject the env vars server-side.
 *
 * The service worker handles background push notifications (when the
 * browser tab is not focused or the app is not open).
 *
 * Registration (done in NotificationPermission component):
 *   navigator.serviceWorker.register('/firebase-messaging-sw.js')
 */

import { NextResponse } from "next/server";

export const dynamic = "force-dynamic"; // Always fresh — no edge caching

export async function GET(): Promise<NextResponse> {
  const config = {
    apiKey:            process.env.NEXT_PUBLIC_FIREBASE_API_KEY            ?? "",
    authDomain:        process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN        ?? "",
    projectId:         process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID         ?? "",
    storageBucket:     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET     ?? "",
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID ?? "",
    appId:             process.env.NEXT_PUBLIC_FIREBASE_APP_ID             ?? "",
  };

  const sw = `
// SanPedroMotoCare — Firebase Messaging Service Worker
// Auto-generated by /firebase-messaging-sw.js route — do not edit manually

importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.0/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config)});

const messaging = firebase.messaging();

// Handle background messages (tab not focused / app not open)
messaging.onBackgroundMessage(function(payload) {
  console.log('[SPM SW] Background message:', payload);

  const notification = payload.notification ?? {};
  const data         = payload.data         ?? {};

  const title = notification.title || 'SanPedroMotoCare';
  const body  = notification.body  || 'Tienes una nueva notificación.';
  const icon  = notification.icon  || '/icons/icon-192.png';
  const badge = '/icons/icon-192.png';
  const url   = data.clickUrl || payload.fcmOptions?.link || '/portal';

  self.registration.showNotification(title, {
    body,
    icon,
    badge,
    tag:                   data.ticketId || 'spm-notification',
    renotify:              true,
    requireInteraction:    false,
    vibrate:               [200, 100, 200],
    data:                  { url },
    actions: [
      { action: 'open',    title: 'Ver detalles' },
      { action: 'dismiss', title: 'Cerrar' },
    ],
  });
});

// Handle notification click
self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  if (event.action === 'dismiss') return;

  const url = event.notification.data?.url || '/portal';

  event.waitUntil(
    clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then(function(clientList) {
        // If app is already open, focus it
        for (const client of clientList) {
          if (client.url.includes(self.location.origin) && 'focus' in client) {
            client.navigate(url);
            return client.focus();
          }
        }
        // Otherwise open a new tab
        if (clients.openWindow) return clients.openWindow(url);
      })
  );
});
`.trim();

  return new NextResponse(sw, {
    status: 200,
    headers: {
      "Content-Type":            "application/javascript; charset=utf-8",
      "Service-Worker-Allowed":  "/",
      "Cache-Control":           "no-cache, no-store, must-revalidate",
    },
  });
}
