import type { Metadata, Viewport } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { AuthProvider } from "@/contexts/AuthContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-display",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: {
    default: "SanPedroMotoCare — Mecánico a Domicilio",
    template: "%s | SanPedroMotoCare",
  },
  description:
    "Mecánicos certificados a domicilio en San Pedro Garza García y área metropolitana de Monterrey. Afinaciones, frenos, eléctricas y más.",
  keywords: [
    "mecánico a domicilio",
    "moto",
    "San Pedro Garza García",
    "Monterrey",
    "reparación moto",
    "mantenimiento motocicleta",
    "mecánico moto Monterrey",
    "taller moto a domicilio",
  ],
  authors: [{ name: "SanPedroMotoCare" }],
  creator: "SanPedroMotoCare",
  publisher: "SanPedroMotoCare",
  formatDetection: { telephone: true },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL ?? "https://sanpedromotocare.com"),
  openGraph: {
    type: "website",
    locale: "es_MX",
    url: "/",
    siteName: "SanPedroMotoCare",
    title: "SanPedroMotoCare — Mecánico a Domicilio",
    description:
      "Mecánicos certificados a domicilio en San Pedro Garza García. Tu moto lista sin moverte.",
    images: [
      {
        // Dynamic 1200×630 banner generated by /api/og — correct for WhatsApp & Messenger
        url: "/api/og",
        width: 1200,
        height: 630,
        alt: "SanPedroMotoCare — Mecánico Certificado a Domicilio",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "SanPedroMotoCare — Mecánico a Domicilio",
    description: "Mecánicos certificados a domicilio en San Pedro Garza García.",
    images: ["/api/og"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "SPM Mecánico",
    statusBarStyle: "black-translucent",
  },
  icons: {
    // favicon.png = nuevo logo oficial SanPedroMotoCare (logoSPMC.png)
    icon: [
      { url: "/favicon.png",       type: "image/png"                     },
      { url: "/favicon.png",       type: "image/png", sizes: "32x32"     },
      { url: "/favicon.png",       type: "image/png", sizes: "96x96"     },
      { url: "/icons/icon-192.png", sizes: "192x192",  type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512",  type: "image/png" },
    ],
    apple: [
      { url: "/icons/icon-192.png"                  },
      { url: "/icons/icon-192.png", sizes: "180x180" },
      { url: "/icons/icon-192.png", sizes: "152x152" },
      { url: "/icons/icon-192.png", sizes: "120x120" },
    ],
    shortcut:"/favicon.png",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="es"
      className={`${poppins.variable} ${inter.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "AutoRepair",
              name: "SanPedroMotoCare",
              description: "Mecánicos certificados de motocicletas a domicilio en San Pedro Garza García y área metropolitana de Monterrey.",
              url: "https://sanpedromotocare.com",
              telephone: "+52-81-8168-4518",
              email: "admin@sanpedromotocare.com",
              image: "https://sanpedromotocare.com/images/logo.png",
              logo: "https://sanpedromotocare.com/images/logo.png",
              priceRange: "$$",
              currenciesAccepted: "MXN",
              paymentAccepted: "Cash, Credit Card, Debit Card, Bank Transfer",
              areaServed: [
                { "@type": "City", name: "San Pedro Garza García", containedInPlace: { "@type": "State", name: "Nuevo León" } },
                { "@type": "City", name: "Monterrey", containedInPlace: { "@type": "State", name: "Nuevo León" } },
                { "@type": "City", name: "Guadalupe", containedInPlace: { "@type": "State", name: "Nuevo León" } },
                { "@type": "City", name: "Apodaca", containedInPlace: { "@type": "State", name: "Nuevo León" } },
              ],
              address: {
                "@type": "PostalAddress",
                addressLocality: "San Pedro Garza García",
                addressRegion: "Nuevo León",
                addressCountry: "MX",
              },
              openingHoursSpecification: [
                {
                  "@type": "OpeningHoursSpecification",
                  dayOfWeek: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
                  opens: "07:00",
                  closes: "21:00",
                },
              ],
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+52-81-8168-4518",
                contactType: "customer service",
                email: "admin@sanpedromotocare.com",
                availableLanguage: "Spanish",
                contactOption: "TollFree",
              },
              sameAs: [
                "https://instagram.com/sanpedromotocare",
                "https://facebook.com/sanpedromotocare",
              ],
            }),
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var t = localStorage.getItem('spm-theme');
                  if (t !== 'light') {
                    document.documentElement.classList.add('dark');
                  }
                } catch(e) {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-screen font-[var(--font-body)] bg-[var(--bg-primary)] text-[var(--text-primary)] transition-colors duration-300">
        <ThemeProvider>
          <LanguageProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
